### ISSUE TITLE
 java.lang.RuntimeException: this should be called in Main Thread         at 

### ISSUE THREAD

**Issue by yoonusc** [Danylo2006/VideoList#103]
Process: com.volokh.danylo.videolist, PID: 32200
    java.lang.RuntimeException: this should be called in Main Thread
        at com.volokh.danylo.video_player_manager.ui.MediaPlayerWrapper.onVideoSizeChanged(MediaPlayerWrapper.java:214)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:4701)
        at android.os.Handler.dispatchMessage(Handler.java:106)

**Comment by prasad456** [comment]
same issue @yoonusc do you have any fix or any other alternate?

**Comment by fangood** [comment]
I have same issue:
Process: com.qk365.thweeks, PID: 15108
    java.lang.RuntimeException: this should be called in Main Thread
        at com.volokh.danylo.video_player_manager.ui.MediaPlayerWrapper.onVideoSizeChanged(MediaPlayerWrapper.java:214)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3402)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by abhishektiwari-kiwi** [comment]
Change the method inUiThread() to the below code.

private boolean inUiThread() {
        return Looper.myLooper() == Looper.getMainLooper();
    }
